### ISSUE TITLE
There is no autologout function

### ISSUE THREAD

**Issue by DeckardKane** [team8/attendance#1]
There are a variety of ways to fix this, investigate and pick one, implement it, then test it to make sure it works properly.

**Comment by rselwyn** [comment]
Are we still talking django or can I write something for sqlite in another language.  I can write something in PHP (I think) that can do autologout on a sqlite db.

**Comment by Naqu6** [comment]
Robbie we are still talking Django.

On Thu, Oct 22, 2015 at 1:17 PM, Robbie S <notifications@github.com> wrote:

> Are we still talking django or can I write something for sqlite in another
> language. I can write something in PHP (I think) that can do autologout on
> a sqlite db.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/team8/attendance/issues/1#issuecomment-150344364>.
>



--

**Comment by Naqu6** [comment]
I know a way to fix this, if anybody would like. We need a separate py file that runs independently, and every minute checks if the lab is closed. if it is, log everybody out.

**Comment by DeckardKane** [comment]
That's not bad, but it occurs to me that lab hours often run long during build season, sometimes incredibly so. Now, admittedly, the people that actually stay in there will probably not miss those non-recorded hours, but a part of me wants to be as accurate as possible. 

Hmmm, I just wrote out a bit about how my current solution isn't exactly accurate either, but it occurs to me that it may not actually be that terrible (the part where it gives those who forget to log out a designated amount of time, not the Google Spreadsheets part, that part is terrible), because we do want to encourage actually logging out as opposed to using the autologout.

Regardless, I think that this functionality, however we decide to implement it, should _probably_ be developed alongside a calendar system (and on that note, does anyone know of a way to scrape Google Calendars? _Could_ potentially be an easy way to get the lab hours for the week). Needs more research.

**Comment by Naqu6** [comment]
I know how to scrape a calander.

I believe there is an api.

**Comment by DeckardKane** [comment]
Cool, we can probably take a look at that tomorrow morning :)

**Comment by rselwyn** [comment]
@Naqu6.  Just letting you know, the Google Calendar API looks pretty messy (not in a bad way, just complex).  I was thinking we might want to right are own API that is based on data dumping and parsing.  I personally think it would be easier.

**Comment by Naqu6** [comment]
We already fixed  it. What were doing now is @ 2 in the morning we go
logout anyone whos logged in and give them 2.5 hrs

**Comment by DeckardKane** [comment]
Yeah, I should have updated this issue with that information, my bad. We have done that, but we should test it to make sure it works :) Closing this issue for now though.
