### ISSUE TITLE
Django and Apache don't play nice

### ISSUE THREAD

**Issue by DeckardKane** [team8/attendance#11]
So when running python manage.py runserver, I get an error, as Apache uses the port runserver uses by default (8000 I believe). I tried running the server with additional ip and port arguments, in the console it looked like everything was running successfully, but I was unable to connect via a web browser. Advice?

**Comment by Naqu6** [comment]
Did you go to pturnbull.me:8000?

**Comment by DeckardKane** [comment]
http://puu.sh/lrVeF/f9931fb05f.png

**Comment by Naqu6** [comment]
Are you running python manage.py runserver 0.0.0.0:8000?

**Comment by DeckardKane** [comment]
That one just gives me "Port is in use"

**Comment by Naqu6** [comment]
Ok that means that your server already has something running on that port.

This could be a run away Django project, or something else.

To check,
Do the command: netstat -lnptu
Please send me the output

**Comment by DeckardKane** [comment]
http://puu.sh/lrZ06/8d0ea04fa4.png

**Comment by Naqu6** [comment]
You've got a runaway django program on port 8000, pid 5896.

Type kill 5896
In a shell to stop it, then run the command again

**Comment by Naqu6** [comment]
Or to configure it with apache read this:
https://docs.djangoproject.com/en/1.8/howto/deployment/wsgi/modwsgi/

**Comment by DeckardKane** [comment]
Will do, will update with results later. Thanks Ryan!

**Comment by Naqu6** [comment]
Great! Happy to help

**Comment by DeckardKane** [comment]
Progress is being made on deploying. I can successfully run the application off the server and access it elsewhere. I still need to do some work with Mod_WSGI and some Apache config work in order to get it to be accessible over a privileged port.
