### ISSUE TITLE
Run Away Threads....

### ISSUE THREAD

**Issue by Naqu6** [team8/attendance#13]
Some times our Django Programs run away and still use a port......

**Comment by Naqu6** [comment]
How to fix:
`ps aux | grep -i manage` in a shell
will be a list of processes like this:
`4770     8264  0.0  1.9 546948 40904 ?        S    Sep19   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8006
14770    15215  0.0  2.7 536708 56420 ?        S    Sep13   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8001
14770    30144  0.0  2.1 612488 44912 ?        S    Sep18   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8000
14770    30282  0.0  1.9 678024 40104 ?        S    Sep18   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8002
14770    30592  0.0  2.1 678024 45008 ?        S    Sep18   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8003
14770    30743  0.0  2.1 678024 45044 ?        S    Sep18   0:00 /usr/local/bin/python manage.py runserver 0.0.0.0:8004`

Note PID (Process Ids):
Type: `kill -9 pid YOUR_PID_HERE`
Closing

**Comment by Naqu6** [comment]
@DeckardKane This is how you do it

**Comment by DeckardKane** [comment]
Okay, good to know, but is there a way I can prevent it from "running away" in the first place? Is it because of the whole lack-of-break-key issue?
