### ISSUE TITLE
Certain entries in the database don't scan

### ISSUE THREAD

**Issue by rselwyn** [team8/attendance#39]
(Specifically my ID).

There is a student entry for me in the DB, but my ID won't scan on the system.

**Comment by Naqu6** [comment]
Is ur id in the db

**Comment by rselwyn** [comment]
Yes it is.

**Comment by Naqu6** [comment]
Tell peter to check that

**Comment by DeckardKane** [comment]
I am! :)

**Comment by DeckardKane** [comment]
It is a very weird error on multiple levels.

**Comment by DeckardKane** [comment]
Fixed. See issue #43.
