### ISSUE TITLE
I am not in the database

### ISSUE THREAD

**Issue by JoeyKL** [team8/attendance#42]
Whenever I enter my ID, it says I am not in the database. My ID is 95016151. I am Joey Kellison-Linn.

**Comment by DeckardKane** [comment]
Still? That's frustrating. Will take a look.

**Comment by rselwyn** [comment]
@DeckardKane That would mean @Naqu6's code to get name's from the PAUSD database isn't working.

**Comment by Naqu6** [comment]
@deckardcain is the code live?

**Comment by Naqu6** [comment]
On the dev server code runs fine

**Comment by DeckardKane** [comment]
Yep, code has been live since yesterday.

**Comment by Naqu6** [comment]
K i'll check

**Comment by Naqu6** [comment]
It works
