### ISSUE TITLE
The code to pull data from the database isn't working.

### ISSUE THREAD

**Issue by rselwyn** [team8/attendance#43]
We have a few reports ( #42 , #39 ) about the code to pull the name on IDs not in the database not working.

**Comment by DeckardKane** [comment]
Found issue, it's not the code, it's me being dumb and making database changes on zero sleep.

**Comment by DeckardKane** [comment]
(Just for reference, the issue was that Joey's ID# was set to the same as Robbie's. The good news is that we don't break the box when that happens now, so that's good. I have rectified this, Joey's ID# is set properly and Robbie's ID# has been returned to its initial value.)
